
  # IP-RANGE-CONTROLLED no longer works... probably needs IP range refresh, cannot get throughto api.sonar
  # SonarQube:
  #   runs-on: ip-range-controlled
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0
    
  #   - name: SonarQube Scan
  #     uses: sonarsource/sonarqube-scan-action@v5.1.0
  #     continue-on-error: true
  #     env:
  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}