# sonarqube-private-repo.yml
name: SonarQube scan for private repositories
# configuration @ https://github.com/marketplace/actions/official-sonarqube-scan

on:
  workflow_call:
    # all secrets are inherited from the calling workflow, typically SONAR_TOKEN, SONAR_HOST_URL
    inputs:
      perform-build: 
        required: false
        type: boolean
      build-profile:  # TODO: implmenet this flag - chef360 container build flags, etc
        required: false
        type: string
      language: 
        required: false
        type: string
      report-unit-test-coverage: 
        required: false
        type: boolean
      report-to-atlassian-dashboard: 
        required: false
        type: boolean
      quality-product-name:
        required: false
        type: string
      quality-sonar-app-name:
        required: false
        type: string
      quality-testing-type:
        required: false
        type: string
      quality-service-name:
        required: false
        type: string
      quality-junit-report:
        required: false
        type: string
      visibility: # TODO: simplify the sonar step by bringing in the other variants (private, public, internal) from the calling workflow
        required: false
        type: string
      go-private-modules:
        required: false
        type: string
      udf1:
        required: false
        type: string
      udf2:
        required: false
        type: string
      udf3:
        required: false
        type: string

jobs:
  SonarQube:
    runs-on: ubuntu-latest-4-cores
    permissions: 
      id-token: write
      contents: read
    steps:
    - name: Checkout
      if: ${{ inputs.visibility == 'private' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: SonarQube Scan
      if: ${{ inputs.visibility == 'private' }}
      uses: sonarsource/sonarqube-scan-action@v5.3.1
      # was uses: sonarsource/sonarqube-scan-action@v5.1.0
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        