# blackduck-srm-sbom.yml
# from https://documentation.blackduck.com/bundle/bridge/page/documentation/c_github-srm.html
name: Blackduck SRM and SBOM integration

# alternative - https://github.com/marketplace/actions/create-black-duck-report 

name: CI-SRM-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: SRM Scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        with:
          ### SCANNING: Required fields
          srm_url: ${{ vars.SRM_URL }}
          srm_apikey: ${{ secrets.SRM_API_KEY }}
          srm_assessment_types: "SCA,SAST" 