# CI pipeline for all Ruby application types on main and release branches
# use stubs/ci-all-ruby-main-stub.yml in your repo to call this common action using workflow_call
name: Ruby main and release branch CI flow

on:
  workflow_call:
    inputs:
    #   message:
    #     required: true
    #     type: string
      language:
        description: 'Primary language in the repository'
        required: true
        type: string
      outputfilename:
        description: 'Name of the SCC output file'
        required: false
        type: string
        default: 'scc-output.txt'
#   workflow_dispatch:
#     inputs:
#       message:
#         required: true
#         type: string

jobs:
#   reusable_echo:
#     name: echo message back
#     runs-on: ubuntu-latest
#     steps:
#       - name: echo
#         run: |
#           echo "Hello ${{ inputs.message }}"

  run-scc:
    uses: chef/common-github-actions/.github/workflows/scc.yml@main
    with:
      outputfilename: ${{ inputs.outputfilename }}

  run-trufflehog:
    uses: chef/common-github-actions/.github/workflows/trufflehog.yml@main
   
  run-sonarqube:
    uses: chef/common-github-actions/.github/workflows/ruby-sonarqube.yml@main
    secrets: inherit
    # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
  