name: SonarQube scan

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  workflow_call:
    
jobs:
  sonarqube:
    # runs-on: ubuntu-latest-4-cores
    runs-on: ip-range-controlled
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: 1.23.6
    
    # - name: Configure git for private modules
    #   env:
    #     GOPRIVATE: github.com/progress-platform-services/*
    #   run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
    
    # - name: Generate coverage files
    #   run: go test -v -coverprofile="coverage.out" ./... 
    # - name: Copy file
    #   run: mkdir -p test/coverage; cp coverage.out test/coverage/coverage.out
    
    - name: SonarQube Scan
      # if: always()
      uses: sonarsource/sonarqube-scan-action@v5.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} - TODO: make this instead of a secret into an organizational variable

