# scc.yml - Generate complexity metrics
# from https://github.com/boyter/scc with flags at # flags like -i js,go,html,css,rb at https://github.com/boyter/scc?tab=readme-ov-file#usage
name: source code complexity scan
    
on:
  workflow_call:
    inputs:
      outputfilename:
        description: 'Name of the SCC output file, do not add file extension'
        required: false
        type: string
        default: 'scc-complexity'

env:
  DEFAULT_FILE_NAME: "scc-complexity"
  DEFAULT_FILE_EXTENSION: ".json"
  DEFAULT_SEPARATOR: "-"        

jobs:
  scc:
    runs-on: ubuntu-latest
    name: 'Complexity and SLOC generation'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and run scc CLI
        run: |
          go install github.com/boyter/scc/v3@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          FILE_PREFIX=$(echo "${{ github.repository }}${{ env.DEFAULT_SEPARATOR }}${{ github.ref_name }}" | sed 's|/|-|g')-$(date +%Y%m%d%H%M%S)
          echo "FILE_PREFIX=${FILE_PREFIX}" >> $GITHUB_ENV
        
          scc -o "${FILE_PREFIX}-${{ inputs.outputfilename }}.txt" 
          scc -o "${FILE_PREFIX}-${{ inputs.outputfilename }}.json" -f json --by-file --sort lines,code,comments,blank
          scc -o "${FILE_PREFIX}-${{ inputs.outputfilename }}.html" -f html --by-file --sort lines,code,comments,blank
        continue-on-error: true
    
      - name: Upload tabular artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.txt'
          path: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.txt'
          retention-days: 30
          overwrite: true
        continue-on-error: true

      - name: Upload JSON detailed artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.json'
          path: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.json'
          retention-days: 30
          overwrite: true
        continue-on-error: true

      - name: Upload HTML detailed artifact
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.html'
          path: '${{ env.FILE_PREFIX }}-${{ inputs.outputfilename }}.html'
          retention-days: 30
          overwrite: true
        continue-on-error: true
