# scc.yml
# from https://github.com/boyter/scc
name: source code complexity scan
    
on:
  workflow_call:
    inputs:
      outputfilename:
        description: 'Name of the SCC output file'
        required: false
        type: string
        default: 'scc-output.txt'

jobs:
  scc:
    runs-on: ubuntu-latest
    name: 'Complexity and SLOC generation'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Generate complexity metrics (using Adapt-API action)
      #   id: scc
      #   uses: Adapt-API/scc-docker-action@master
      # https://github.com/Adapt-API/scc-docker-action 
      # TODO: no longer in marketplace

      #   with:
      #     args: -o ${{ inputs.outputfilename }} -f json --by-file --sort lines,code,comments,blank  
      #     # flags like -i js,go,html,css,rb at https://github.com/boyter/scc?tab=readme-ov-file#usage

      # TODO: add filename date stamp
      - name: Install scc CLI
        run: |
          go install github.com/boyter/scc/v3@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          scc -o ${{ inputs.outputfilename }} -f json --by-file --sort lines,code,comments,blank
        continue-on-error: true
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.outputfilename }}
          path: ${{ inputs.outputfilename }}
          retention-days: 30
          overwrite: true
