# sonarqube-internal-repo.yml
name: SonarQube scan for internal repositories
# configuration @ https://github.com/marketplace/actions/official-sonarqube-scan
# TODO: replace existing sonarqube.yml in PPS repos (like https://github.com/progress-platform-services/chef-node-enrollment-api/blob/main/.github/workflows/sonarqube.yml)
# TODO: remove from PPS code gen, just use the stub

on:
  workflow_call:
    # inputs:
    #   skip-unit-tests:
    #     description: 'Skip unit tests'
    #     required: false
    #     type: boolean
    #     default: false
    
jobs:
  # echo-inputs:
  #   name: 'Echo inputs'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Echo inputs
  #     run: |
  #       echo "Sonarqube scan for INTERNAL repositories, running on ubuntu-latest-4-cores runner"
  #       echo "Sonar host URL ${{ secrets.SONAR_HOST_URL}}"
  # #       echo "Skip unit tests set to ${{ inputs.skip-unit-tests }}"
  
  SonarQube:
    runs-on: ubuntu-latest-4-cores
    steps:
    # unit-tests:
  #   runs-on: ubuntu-latest
  #   if: ${{ inputs.skip-unit-tests == false }}
  #   steps:
  #   - name: Run unit tests
  #     run: | 
  #       echo "Running unit tests..."
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.6

    - name: Configure git for private modules
      env:
        GOPRIVATE: github.com/progress-platform-services/*
      run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Generate coverage files
      run: go test -v -coverprofile="coverage.out" ./... 
    - name: Copy file
      run: mkdir -p test/coverage; cp coverage.out test/coverage/coverage.out          

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v5.1.0
      # was uses: sonarsource/sonarqube-scan-action@master
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    