# sonarqube-internal-repo.yml
name: SonarQube scan for internal repositories
# configuration @ https://github.com/marketplace/actions/official-sonarqube-scan

on:
  workflow_call:
    # inputs:
    #   skip-unit-tests:
    #     description: 'Skip unit tests'
    #     required: false
    #     type: boolean
    #     default: false
    
jobs:
  echo-inputs:
    name: 'Echo inputs'
    runs-on: ubuntu-latest
    steps:
    - name: Echo inputs
      run: |
        echo "Sonarqube scan for INTERNAL repositories, running on ubuntu-latest-4-cores runner"
        echo "Sonar host URL ${{ vars.SONAR_HOST_URL}}"
  #       echo "Skip unit tests set to ${{ inputs.skip-unit-tests }}"
     
  # unit-tests:
  #   runs-on: ubuntu-latest
  #   if: ${{ inputs.skip-unit-tests == false }}
  #   steps:
  #   - name: Run unit tests
  #     run: | 
  #       echo "Running unit tests..."
              

  sonarqube:
    runs-on: ubuntu-latest-4-cores
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      # if: always()
      uses: sonarsource/sonarqube-scan-action@v5.1.0
      continue-on-error: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
