# srcclr.yml
# from https://github.com/Adapt-API/scc-docker-action
name: run srcclr scan


# srcclr scan . --recursive --quick
# srcclr scan .\automate\ --recursive --quick
# needs SRCCLR_API_TOKEN env var...
# srcclr scan --url https://github.com/progress-platform-services/chef-node-management-cli --json=veracode_output --no-upload --recursive --ref=main --scan-analyzers="go mod"
SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}

on:
  workflow_call:
    inputs:
      outputfilename:
        description: 'Name of the SCC output file'
        required: false
        type: string
        default: 'scc-output.txt'

jobs:
  scc:
    runs-on: ubuntu-latest
    name: 'Complexity and SLOC'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate complexity metrics (using Adapt-API action)
        id: scc
        uses: Adapt-API/scc-docker-action@master
        with:
          args: -o ${{ inputs.outputfilename }}
          # --by-file -i js,go,html,css,rb 
          
        #   - name: Echo output to correct file
        #     run: echo -n "${{ steps.scc.outputs.scc }}" >> ${{ inputs.outputfilename }}
         #     #   echo -n "${{ fromJson(steps.scc.outputs.scc)[0].Code }}"       
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.outputfilename }}
          path: ${{ inputs.outputfilename }}
          retention-days: 30
          overwrite: true
